DocumentAdministratif:
    type: entity
    table: document_administratif
    id:
        iddocument:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        nom:
            type: string
            nullable: true
            length: 45
            options:
                fixed: false
        path:
            type: string
            nullable: true
            length: 45
            options:
                fixed: false
    lifecycleCallbacks: {  }
