Formateur:
    type: entity
    table: formateur
    id:
        idformateur:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        cin:
            type: string
            nullable: true
            length: 45
            options:
                fixed: false
        email:
            type: string
            nullable: true
            length: 45
            options:
                fixed: false
        nom:
            type: string
            nullable: true
            length: 45
            options:
                fixed: false
        prenom:
            type: string
            nullable: true
            length: 45
            options:
                fixed: false
        role:
            type: string
            nullable: true
            length: 45
            options:
                fixed: false
    lifecycleCallbacks: {  }
