Groupe:
    type: entity
    table: groupe
    id:
        idgroupe:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        nom:
            type: string
            nullable: true
            length: 45
            options:
                fixed: false
        specialite:
            type: string
            nullable: true
            length: 45
            options:
                fixed: false
        emploi:
            type: string
            nullable: true
            length: 45
            options:
                fixed: false
        cal:
            type: string
            nullable: true
            length: 45
            options:
                fixed: false
        path:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
    lifecycleCallbacks: {  }
