stagiaiarebtp_index:
    path:     /
    defaults: { _controller: "AdminBundle:Stagiaiarebtp:index" }
    methods:  GET

stagiaiarebtp_show:
    path:     /{id}/show
    defaults: { _controller: "AdminBundle:Stagiaiarebtp:show" }
    methods:  GET

stagiaiarebtp_new:
    path:     /new
    defaults: { _controller: "AdminBundle:Stagiaiarebtp:new" }
    methods:  [GET, POST]

stagiaiarebtp_edit:
    path:     /{id}/edit
    defaults: { _controller: "AdminBundle:Stagiaiarebtp:edit" }
    methods:  [GET, POST]

stagiaiarebtp_delete:
    path:     /{id}/delete
    defaults: { _controller: "AdminBundle:Stagiaiarebtp:delete" }
    methods:  DELETE
