verifinscri_index:
    path:     /
    defaults: { _controller: "AdminBundle:VerifInscri:index" }
    methods:  GET

verifinscri_show:
    path:     /{id}/show
    defaults: { _controller: "AdminBundle:VerifInscri:show" }
    methods:  GET

verifinscri_new:
    path:     /new
    defaults: { _controller: "AdminBundle:VerifInscri:new" }
    methods:  [GET, POST]

verifinscri_edit:
    path:     /{id}/edit
    defaults: { _controller: "AdminBundle:VerifInscri:edit" }
    methods:  [GET, POST]

verifinscri_delete:
    path:     /{id}/delete
    defaults: { _controller: "AdminBundle:VerifInscri:delete" }
    methods:  DELETE
